"""Add study hub persistence tables

Revision ID: 37308e7e1978
Revises: 03793f3986b8
Create Date: 2025-12-16 04:01:16.842679

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '37308e7e1978'
down_revision: Union[str, Sequence[str], None] = '03793f3986b8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('study_flashcard_sets',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('document_id', sa.UUID(), nullable=True),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('flashcards', sa.Text(), nullable=True),
    sa.Column('total_cards', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_study_flashcard_sets_document_id'), 'study_flashcard_sets', ['document_id'], unique=False)
    op.create_index(op.f('ix_study_flashcard_sets_user_id'), 'study_flashcard_sets', ['user_id'], unique=False)
    op.create_table('study_notes',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('document_id', sa.UUID(), nullable=True),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('mode', sa.String(length=20), nullable=False),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_study_notes_document_id'), 'study_notes', ['document_id'], unique=False)
    op.create_index(op.f('ix_study_notes_user_id'), 'study_notes', ['user_id'], unique=False)
    op.create_table('study_quiz_sets',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('document_id', sa.UUID(), nullable=True),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('questions', sa.Text(), nullable=True),
    sa.Column('total_questions', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_study_quiz_sets_document_id'), 'study_quiz_sets', ['document_id'], unique=False)
    op.create_index(op.f('ix_study_quiz_sets_user_id'), 'study_quiz_sets', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_study_quiz_sets_user_id'), table_name='study_quiz_sets')
    op.drop_index(op.f('ix_study_quiz_sets_document_id'), table_name='study_quiz_sets')
    op.drop_table('study_quiz_sets')
    op.drop_index(op.f('ix_study_notes_user_id'), table_name='study_notes')
    op.drop_index(op.f('ix_study_notes_document_id'), table_name='study_notes')
    op.drop_table('study_notes')
    op.drop_index(op.f('ix_study_flashcard_sets_user_id'), table_name='study_flashcard_sets')
    op.drop_index(op.f('ix_study_flashcard_sets_document_id'), table_name='study_flashcard_sets')
    op.drop_table('study_flashcard_sets')
    # ### end Alembic commands ###
